# Generated by Django 5.2.2 on 2025-06-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='payment_type',
            field=models.CharField(choices=[('RTGS', 'RTGS'), ('NEFT', 'NEFT'), ('ABS', 'ABS'), ('CHEQUE', 'Cheque')], max_length=10, unique=True),
        ),
    ]
