# Generated by Django 5.2.2 on 2025-06-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='payment_type',
            field=models.CharField(choices=[('RTGS', 'RTGS'), ('NEFT', 'NEFT'), ('ABS', 'ABS'), ('CHEQUE', 'Cheque')], max_length=50, unique=True),
        ),
    ]
