# Generated by Django 5.2.2 on 2025-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymenttype_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='payment_type',
            field=models.CharField(choices=[('RTGS', 'RTGS'), ('NEFT', 'NEFT'), ('ABS', 'ABS'), ('CHEQUE', 'Cheque')], max_length=10, unique=True),
        ),
    ]
