# Generated by Django 5.2.2 on 2025-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymenttype_bank_name_paymenttype_cheque_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={},
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='category_type',
            field=models.CharField(blank=True, choices=[('SNA', 'SNA'), ('NON_SNA', 'NON SNA'), ('CNA', 'CNA')], help_text='Select the payment category (SNA, NON SNA, or CNA).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='payment_type',
            field=models.CharField(choices=[('RTGS', 'RTGS'), ('NEFT', 'NEFT'), ('ABS', 'ABS'), ('CHEQUE', 'Cheque')], default='RTGS', max_length=50),
        ),
    ]
