# Generated by Django 5.2.3 on 2025-06-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SNA', 'SNA'), ('NON_SNA', 'NON SNA'), ('CNA', 'CNA')], default='SNA', max_length=10, verbose_name='Transaction Type')),
                ('payment_type', models.CharField(choices=[('RTGS', 'RTGS'), ('NEFT', 'NEFT'), ('ABS', 'ABS'), ('CHEQUE', 'Cheque')], max_length=10, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Types',
            },
        ),
    ]
